### ISSUE TITLE
Unable to resolve dependency x5 times

### ISSUE THREAD

**Issue by Kwaskoff** [Agorise/bitsy-wallet#1]
I try just build it for my Android phone

and..

Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :graphenejlib:graphenej.
Open File
Show Details

Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve project :graphenejlib:graphenej.
Open File
Show Details

Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve project :graphenejlib:graphenej.
Open File
Show Details

Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve project :graphenejlib:graphenej.
Open File
Show Details

Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve project :graphenejlib:graphenej.

Fix, please

**Comment by Agorise** [comment]
This wallet is not even an Alpha yet. Thank you for your input though, it is appreciated.
